language: d

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-multilib ; fi

arch:
  - amd64
  - arm64 

os:
  - osx
  - linux

d:
 - ldc-beta
 - ldc-1.22.0
 - ldc-1.21.0
 - ldc-1.20.1
 - ldc-1.19.0
 - ldc-1.18.0
 - ldc-1.17.0
 - ldc-1.16.0
 - ldc-1.15.0
 - ldc-1.14.0
 - ldc-1.13.0
 - ldc-1.12.0
 - ldc-1.11.0
 - ldc-1.10.0
 - ldc-1.9.0
 - ldc-1.8.0
 - dmd-beta
 - dmd-2.093.0
 - dmd-2.092.1
 - dmd-2.091.1
 - dmd-2.090.1
 - dmd-2.089.1
 - dmd-2.088.1
 - dmd-2.087.1
 - dmd-2.086.1
 - dmd-2.085.1
 - dmd-2.084.1
 - dmd-2.083.1
 - dmd-2.082.1
 - dmd-2.081.2
 - dmd-2.080.1
 - dmd-2.079.1
 - dmd-2.078.2
 - gdc

matrix:
  allow_failures:
   - d: gdc
     os: osx          # no GDC for OSX
   - d: dmd-2.080.1   # backend bug with optimizations
   - d: dmd-2.079.1   # codegen issues with optimizations
   - d: dmd-2.078.2   # codegen issues with optimizations
   - d: dmd-2.089.1   # weird travis crash on Linux only, did not investigate

script:
  - dub test --compiler=${DC}
  - dub test -b unittest-release --compiler=${DC}
  - dub test -b unittest-inst --compiler=${DC}
  - dub test -b unittest-release-inst --compiler=${DC}
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dub test --compiler=${DC} -a x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dub test -b unittest-release --compiler=${DC} -a x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dub test -b unittest-inst --compiler=${DC} -a x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dub test -b unittest-release-inst --compiler=${DC} -a x86 ; fi  
