language: d

os:
  - osx
  - linux

d:
 - ldc-beta
 - ldc-1.16.0
 - ldc-1.15.0
 - ldc-1.14.0
 - ldc-1.13.0
 - ldc-1.12.0
 - ldc-1.11.0
 - ldc-1.10.0
 - ldc-1.9.0
 - ldc-1.8.0
 - dmd-beta
 - dmd-2.087.0
 - dmd-2.086.1
 - dmd-2.085.1
 - dmd-2.084.1
 - dmd-2.083.1
 - dmd-2.082.1
 - dmd-2.081.2
 - dmd-2.080.1
 - dmd-2.079.1
 - dmd-2.078.2
 - gdc

matrix:
  allow_failures:
   - d: gdc
   - d: dmd-2.079.1   # codegen issues with optimizations
   - d: dmd-2.078.2   # codegen issues with optimizations

# Note: 32-bit x86 isn't tested anymore
script:
  - dub test --compiler=${DC}
  - dub test -b unittest-release --compiler=${DC}
