language: d

os:
  - osx
  - linux

d:
 - ldc-beta
 - ldc-1.12.0
 - ldc-1.11.0
 - ldc-1.10.0
 - ldc-1.9.0
 - ldc-1.8.0
 - ldc-1.7.0
 - ldc-1.6.0
 - ldc-1.5.0
 - ldc-1.4.0
 - ldc-1.3.0
 - dmd-beta
 - dmd-2.083.1
 - dmd-2.082.1
 - dmd-2.081.2
 - dmd-2.080.1
 - dmd-2.079.1
 - dmd-2.078.2
 - dmd-2.077.1
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1
 - gdc

# ldc 1.2 to 1.5 don't work on Travis OSX because DUB requires too recent libcurl
matrix:
  allow_failures:
   - d: gdc  
  exclude:
  - d: ldc-1.3.0
    os: osx
  - d: ldc-1.4.0
    os: osx

# Note: 32-bit x86 isn't tested for Linux
script:
  - dub test --compiler=${DC}
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 ; fi
