name: arm64
on: [push, pull_request]

jobs:
    test:
        name: Dub Tests
        strategy:
            matrix:
                os: [macos-12]
                dc: 
                    - ldc-latest
                    - ldc-1.28.1

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}

            # Note: debug info disabled on M1 because of
            # https://github.com/ldc-developers/ldc/issues/3864

            - name: Unittest with unittest-release configuration
              run: dub test -b unittest-release -a arm64-apple-macos

            - name: Unittest with unittest-release-inst configuration
              run: dub test -b unittest-release-inst -a arm64-apple-macos
              