name: gdc
on: [push, pull_request]

jobs:
    test:
        name: Dub Tests
        strategy:
            matrix:
                os: [ubuntu-20.04]
                dc: 
                    - ldc-latest 

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - name: Install GDC
              run: sudo apt install gdc

            - name: Install DUB
              run: sudo apt install dub

            - name: Install libcurl
              run: sudo apt install libcurl4-gnutls-dev

            - name: Vanilla unittest
              run: dub test -a x86_64 --compiler gdc

            - name: Unittest with default configuration
              run: dub test -a x86_64 --compiler gdc -b unittest-release

            - name: Unittest with unittest-inst configuration
              run: dub test -a x86_64 --compiler gdc -b unittest-inst

            - name: Unittest with unittest-release-inst configuration
              run: dub test -a x86_64 --compiler gdc -b unittest-release-inst
 
